# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under dbx_llmops_demo/resources/*
# and dbx_llmops_demo/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for dbx_llmops_demo Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./dbx_llmops_demo

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: dbx_llmops_demo-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t ang_nara_catalog
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t ang_nara_catalog
